// Generated by tools/build_rules.py

private rule helper_dob_en : helper
{
    strings:
        $value = /(^|[\r\n{,;])[ \t]*["']?(DOB)["']?[ \t]*([:=][ \t]*|[ \t]+)["']?(18|19|20)[0-9]{2}[-.\/](0?[1-9]|1[0-2])[-.\/](0?[1-9]|[12][0-9]|3[01])\b/ nocase
    condition:
        $value
}

private rule helper_dob_long_en : helper
{
    strings:
        $value = /(^|[\r\n{,;])[ \t]*["']?(date[_ \t-]*of[_ \t-]*birth)["']?[ \t]*([:=][ \t]*|[ \t]+)["']?(18|19|20)[0-9]{2}[-.\/](0?[1-9]|1[0-2])[-.\/](0?[1-9]|[12][0-9]|3[01])\b/ nocase
    condition:
        $value
}

private rule helper_dob_fr : helper
{
    strings:
        $value = /(^|[\r\n{,;])[ \t]*["']?(DDN)["']?[ \t]*([:=][ \t]*|[ \t]+)["']?(18|19|20)[0-9]{2}[-.\/](0?[1-9]|1[0-2])[-.\/](0?[1-9]|[12][0-9]|3[01])\b/ nocase
    condition:
        $value
}

private rule helper_dob_long_fr : helper
{
    strings:
        $value = /(^|[\r\n{,;])[ \t]*["']?(date[_ \t-]*de[_ \t-]*naissance)["']?[ \t]*([:=][ \t]*|[ \t]+)["']?(18|19|20)[0-9]{2}[-.\/](0?[1-9]|1[0-2])[-.\/](0?[1-9]|[12][0-9]|3[01])\b/ nocase
    condition:
        $value
}
