// Generated by tools/build_rules.py

private rule helper_pri_en : helper
{
    strings:
        $value = /(^|[\r\n{,;])[ \t]*["']?(PRI)["']?[ \t]*([:=][ \t]*|[ \t]+)["']?([0-9]{8,9}|[0-9]{2,3}[-. ][0-9]{3}[-. ][0-9]{3})\b/ nocase
    condition:
        $value
}

private rule helper_pri_long_en : helper
{
    strings:
        $value = /(^|[\r\n{,;])[ \t]*["']?(personal[_ \t-]*record[_ \t-]*identifier)["']?[ \t]*([:=][ \t]*|[ \t]+)["']?([0-9]{8,9}|[0-9]{2,3}[-. ][0-9]{3}[-. ][0-9]{3})\b/ nocase
    condition:
        $value
}

private rule helper_cidp_fr : helper
{
    strings:
        $value = /(^|[\r\n{,;])[ \t]*["']?(CIDP)["']?[ \t]*([:=][ \t]*|[ \t]+)["']?([0-9]{8,9}|[0-9]{2,3}[-. ][0-9]{3}[-. ][0-9]{3})\b/ nocase
    condition:
        $value
}

private rule helper_cidp_long_fr : helper
{
    strings:
        $value = /(^|[\r\n{,;])[ \t]*["']?(code[_ \t-]*d('|\xE2\x80\x99)identification[_ \t-]*de[_ \t-]*dossier[_ \t-]*personnel)["']?[ \t]*([:=][ \t]*|[ \t]+)["']?([0-9]{8,9}|[0-9]{2,3}[-. ][0-9]{3}[-. ][0-9]{3})\b/ nocase
    condition:
        $value
}

private rule helper_sin_en : helper
{
    strings:
        $value = /(^|[\r\n{,;])[ \t]*["']?(SIN)["']?[ \t]*([:=][ \t]*|[ \t]+)["']?([0-9]{9}|[0-9]{3}[-. ][0-9]{3}[-. ][0-9]{3})\b/ nocase
    condition:
        $value
}

private rule helper_sin_long_en : helper
{
    strings:
        $value = /(^|[\r\n{,;])[ \t]*["']?(social[_ \t-]*insurance[_ \t-]*number)["']?[ \t]*([:=][ \t]*|[ \t]+)["']?([0-9]{9}|[0-9]{3}[-. ][0-9]{3}[-. ][0-9]{3})\b/ nocase
    condition:
        $value
}

private rule helper_nas_fr : helper
{
    strings:
        $value = /(^|[\r\n{,;])[ \t]*["']?(NAS)["']?[ \t]*([:=][ \t]*|[ \t]+)["']?([0-9]{9}|[0-9]{3}[-. ][0-9]{3}[-. ][0-9]{3})\b/ nocase
    condition:
        $value
}

private rule helper_nas_long_fr : helper
{
    strings:
        $value = /(^|[\r\n{,;])[ \t]*["']?(num(e|\xC3\xA9|\xC3\x89)ro[_ \t-]*d('|\xE2\x80\x99)assurance[_ \t-]*sociale)["']?[ \t]*([:=][ \t]*|[ \t]+)["']?([0-9]{9}|[0-9]{3}[-. ][0-9]{3}[-. ][0-9]{3})\b/ nocase
    condition:
        $value
}
