// Generated by tools/build_rules.py

private rule helper_first_en : helper
{
    strings:
        $value = /(^|[\r\n{,;])[ \t]*["']?(first[_ \t-]*name)["']?[ \t]*[:=][ \t]*["']?([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])(([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])|['-]){0,39}([ \t]+([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])(([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])|['-]){0,39}){0,2}(["']|[ \t,;}\r\n]|$)/ nocase
    condition:
        $value
}

private rule helper_given_en : helper
{
    strings:
        $value = /(^|[\r\n{,;])[ \t]*["']?(given[_ \t-]*name)["']?[ \t]*[:=][ \t]*["']?([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])(([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])|['-]){0,39}([ \t]+([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])(([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])|['-]){0,39}){0,2}(["']|[ \t,;}\r\n]|$)/ nocase
    condition:
        $value
}

private rule helper_last_en : helper
{
    strings:
        $value = /(^|[\r\n{,;])[ \t]*["']?(last[_ \t-]*name)["']?[ \t]*[:=][ \t]*["']?([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])(([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])|['-]){0,39}([ \t]+([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])(([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])|['-]){0,39}){0,2}(["']|[ \t,;}\r\n]|$)/ nocase
    condition:
        $value
}

private rule helper_family_en : helper
{
    strings:
        $value = /(^|[\r\n{,;])[ \t]*["']?(family[_ \t-]*name)["']?[ \t]*[:=][ \t]*["']?([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])(([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])|['-]){0,39}([ \t]+([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])(([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])|['-]){0,39}){0,2}(["']|[ \t,;}\r\n]|$)/ nocase
    condition:
        $value
}

private rule helper_surname_en : helper
{
    strings:
        $value = /(^|[\r\n{,;])[ \t]*["']?(surname)["']?[ \t]*[:=][ \t]*["']?([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])(([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])|['-]){0,39}([ \t]+([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])(([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])|['-]){0,39}){0,2}(["']|[ \t,;}\r\n]|$)/ nocase
    condition:
        $value
}

private rule helper_full_en : helper
{
    strings:
        $value = /(^|[\r\n{,;])[ \t]*["']?((full[_ \t-]*name|name))["']?[ \t]*[:=][ \t]*["']?([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])(([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])|['-]){0,39}[ \t]+([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])(([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])|['-]){0,39}([ \t]+([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])(([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])|['-]){0,39}){0,2}(["']|[ \t,;}\r\n]|$)/ nocase
    condition:
        $value
}

private rule helper_first_fr : helper
{
    strings:
        $value = /(^|[\r\n{,;])[ \t]*["']?(pr(e|\xC3\xA9|\xC3\x89)nom)["']?[ \t]*[:=][ \t]*["']?([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])(([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])|['-]){0,39}([ \t]+([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])(([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])|['-]){0,39}){0,2}(["']|[ \t,;}\r\n]|$)/ nocase
    condition:
        $value
}

private rule helper_last_fr : helper
{
    strings:
        $value = /(^|[\r\n{,;])[ \t]*["']?(nom[_ \t-]*de[_ \t-]*famille)["']?[ \t]*[:=][ \t]*["']?([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])(([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])|['-]){0,39}([ \t]+([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])(([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])|['-]){0,39}){0,2}(["']|[ \t,;}\r\n]|$)/ nocase
    condition:
        $value
}

private rule helper_full_fr : helper
{
    strings:
        $value = /(^|[\r\n{,;])[ \t]*["']?(nom)["']?[ \t]*[:=][ \t]*["']?([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])(([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])|['-]){0,39}[ \t]+([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])(([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])|['-]){0,39}([ \t]+([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])(([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])|['-]){0,39}){0,2}(["']|[ \t,;}\r\n]|$)/ nocase
    condition:
        $value
}
