// Generated by tools/build_rules.py; requires structured field normalization.

rule flag_protected_en : security_marking classification
{
    meta:
        title = "Protected flag is enabled"
        severity = "LOW"
        suggested_classification = "Protected"
        evidence_model = "marking"
        assessment = "review_required"
    strings:
        $marking = /(^|[\r\n])[ \t]*"Protected"[ \t]*:[ \t]*"true"[ \t]*(\r?\n|$)/ nocase
    condition:
        $marking
}

rule flag_protected_fr : security_marking classification
{
    meta:
        title = "Protégé flag is enabled"
        severity = "LOW"
        suggested_classification = "Protected"
        evidence_model = "marking"
        assessment = "review_required"
    strings:
        $marking = /(^|[\r\n])[ \t]*"Prot(e|\xC3\xA9|\xC3\x89)g(e|\xC3\xA9|\xC3\x89)"[ \t]*:[ \t]*"true"[ \t]*(\r?\n|$)/ nocase
    condition:
        $marking
}

rule flag_protected_a_en : security_marking classification
{
    meta:
        title = "Protected A flag is enabled"
        severity = "MEDIUM"
        suggested_classification = "Protected A"
        evidence_model = "marking"
        assessment = "review_required"
    strings:
        $marking = /(^|[\r\n])[ \t]*"Protected[ _-]+A"[ \t]*:[ \t]*"true"[ \t]*(\r?\n|$)/ nocase
    condition:
        $marking
}

rule flag_protected_a_fr : security_marking classification
{
    meta:
        title = "Protégé A flag is enabled"
        severity = "MEDIUM"
        suggested_classification = "Protected A"
        evidence_model = "marking"
        assessment = "review_required"
    strings:
        $marking = /(^|[\r\n])[ \t]*"Prot(e|\xC3\xA9|\xC3\x89)g(e|\xC3\xA9|\xC3\x89)[ _-]+A"[ \t]*:[ \t]*"true"[ \t]*(\r?\n|$)/ nocase
    condition:
        $marking
}

rule flag_protected_b_en : security_marking classification
{
    meta:
        title = "Protected B flag is enabled"
        severity = "HIGH"
        suggested_classification = "Protected B"
        evidence_model = "marking"
        assessment = "review_required"
    strings:
        $marking = /(^|[\r\n])[ \t]*"Protected[ _-]+B"[ \t]*:[ \t]*"true"[ \t]*(\r?\n|$)/ nocase
    condition:
        $marking
}

rule flag_protected_b_fr : security_marking classification
{
    meta:
        title = "Protégé B flag is enabled"
        severity = "HIGH"
        suggested_classification = "Protected B"
        evidence_model = "marking"
        assessment = "review_required"
    strings:
        $marking = /(^|[\r\n])[ \t]*"Prot(e|\xC3\xA9|\xC3\x89)g(e|\xC3\xA9|\xC3\x89)[ _-]+B"[ \t]*:[ \t]*"true"[ \t]*(\r?\n|$)/ nocase
    condition:
        $marking
}

rule flag_protected_c_en : security_marking classification
{
    meta:
        title = "Protected C flag is enabled"
        severity = "CRITICAL"
        suggested_classification = "Protected C"
        evidence_model = "marking"
        assessment = "review_required"
    strings:
        $marking = /(^|[\r\n])[ \t]*"Protected[ _-]+C"[ \t]*:[ \t]*"true"[ \t]*(\r?\n|$)/ nocase
    condition:
        $marking
}

rule flag_protected_c_fr : security_marking classification
{
    meta:
        title = "Protégé C flag is enabled"
        severity = "CRITICAL"
        suggested_classification = "Protected C"
        evidence_model = "marking"
        assessment = "review_required"
    strings:
        $marking = /(^|[\r\n])[ \t]*"Prot(e|\xC3\xA9|\xC3\x89)g(e|\xC3\xA9|\xC3\x89)[ _-]+C"[ \t]*:[ \t]*"true"[ \t]*(\r?\n|$)/ nocase
    condition:
        $marking
}

rule flag_classified_en : security_marking classification
{
    meta:
        title = "Classified flag is enabled"
        severity = "LOW"
        suggested_classification = "Classified"
        evidence_model = "marking"
        assessment = "review_required"
    strings:
        $marking = /(^|[\r\n])[ \t]*"Classified"[ \t]*:[ \t]*"true"[ \t]*(\r?\n|$)/ nocase
    condition:
        $marking
}

rule flag_classified_fr : security_marking classification
{
    meta:
        title = "Classifié flag is enabled"
        severity = "LOW"
        suggested_classification = "Classified"
        evidence_model = "marking"
        assessment = "review_required"
    strings:
        $marking = /(^|[\r\n])[ \t]*"Classifi(e|\xC3\xA9|\xC3\x89)"[ \t]*:[ \t]*"true"[ \t]*(\r?\n|$)/ nocase
    condition:
        $marking
}

rule flag_confidential_en : security_marking classification
{
    meta:
        title = "Confidential flag is enabled"
        severity = "MEDIUM"
        suggested_classification = "Confidential"
        evidence_model = "marking"
        assessment = "review_required"
    strings:
        $marking = /(^|[\r\n])[ \t]*"Confidential"[ \t]*:[ \t]*"true"[ \t]*(\r?\n|$)/ nocase
    condition:
        $marking
}

rule flag_confidential_fr : security_marking classification
{
    meta:
        title = "Confidentiel flag is enabled"
        severity = "MEDIUM"
        suggested_classification = "Confidential"
        evidence_model = "marking"
        assessment = "review_required"
    strings:
        $marking = /(^|[\r\n])[ \t]*"Confidentiel"[ \t]*:[ \t]*"true"[ \t]*(\r?\n|$)/ nocase
    condition:
        $marking
}

rule flag_secret : security_marking classification
{
    meta:
        title = "Secret flag is enabled"
        severity = "HIGH"
        suggested_classification = "Secret"
        evidence_model = "marking"
        assessment = "review_required"
    strings:
        $marking = /(^|[\r\n])[ \t]*"Secret"[ \t]*:[ \t]*"true"[ \t]*(\r?\n|$)/ nocase
    condition:
        $marking
}

rule flag_top_secret_en : security_marking classification
{
    meta:
        title = "Top Secret flag is enabled"
        severity = "CRITICAL"
        suggested_classification = "Top Secret"
        evidence_model = "marking"
        assessment = "review_required"
    strings:
        $marking = /(^|[\r\n])[ \t]*"Top[ _-]+Secret"[ \t]*:[ \t]*"true"[ \t]*(\r?\n|$)/ nocase
    condition:
        $marking
}

rule flag_top_secret_fr : security_marking classification
{
    meta:
        title = "Très secret flag is enabled"
        severity = "CRITICAL"
        suggested_classification = "Top Secret"
        evidence_model = "marking"
        assessment = "review_required"
    strings:
        $marking = /(^|[\r\n])[ \t]*"Tr(e|\xC3\xA8|\xC3\x88)s[ _-]+secret"[ \t]*:[ \t]*"true"[ \t]*(\r?\n|$)/ nocase
    condition:
        $marking
}

rule flag_unclassified_en : security_marking classification
{
    meta:
        title = "Unclassified flag is enabled"
        severity = "LOW"
        suggested_classification = "Unclassified"
        evidence_model = "marking"
        assessment = "review_required"
    strings:
        $marking = /(^|[\r\n])[ \t]*"Unclassified"[ \t]*:[ \t]*"true"[ \t]*(\r?\n|$)/ nocase
    condition:
        $marking
}

rule flag_unclassified_fr : security_marking classification
{
    meta:
        title = "Non classifié flag is enabled"
        severity = "LOW"
        suggested_classification = "Unclassified"
        evidence_model = "marking"
        assessment = "review_required"
    strings:
        $marking = /(^|[\r\n])[ \t]*"Non[ _-]+classifi(e|\xC3\xA9|\xC3\x89)"[ \t]*:[ \t]*"true"[ \t]*(\r?\n|$)/ nocase
    condition:
        $marking
}

rule flag_protected_when_completed_en : security_marking classification
{
    meta:
        title = "Protected when Completed flag is enabled"
        severity = "LOW"
        suggested_classification = "Protected when Completed"
        evidence_model = "marking"
        assessment = "review_required"
    strings:
        $marking = /(^|[\r\n])[ \t]*"Protected[ _-]+when[ _-]+Completed"[ \t]*:[ \t]*"true"[ \t]*(\r?\n|$)/ nocase
    condition:
        $marking
}

rule flag_protected_when_completed_fr : security_marking classification
{
    meta:
        title = "Protégé lorsque rempli flag is enabled"
        severity = "LOW"
        suggested_classification = "Protected when Completed"
        evidence_model = "marking"
        assessment = "review_required"
    strings:
        $marking = /(^|[\r\n])[ \t]*"Prot(e|\xC3\xA9|\xC3\x89)g(e|\xC3\xA9|\xC3\x89)[ _-]+lorsque[ _-]+rempli"[ \t]*:[ \t]*"true"[ \t]*(\r?\n|$)/ nocase
    condition:
        $marking
}
