// Generated by tools/build_rules.py; shared helpers plus reportable evidence.

rule personal_pri_en : personal_information classification
{
    meta:
        title = "Personnel identifier with a name (EN)"
        severity = "MEDIUM"
        suggested_classification = "Protected A"
        assessment = "review_required"
        evidence_model = "identifier_and_name"
        match_scope = "file"
    strings:
        $identifier = /((^|[\r\n{,;])[ \t]*["']?(PRI)["']?[ \t]*([:=][ \t]*|[ \t]+)["']?([0-9]{8,9}|[0-9]{2,3}[-. ][0-9]{3}[-. ][0-9]{3})\b|(^|[\r\n{,;])[ \t]*["']?(personal[_ \t-]*record[_ \t-]*identifier)["']?[ \t]*([:=][ \t]*|[ \t]+)["']?([0-9]{8,9}|[0-9]{2,3}[-. ][0-9]{3}[-. ][0-9]{3})\b)/ nocase
        $full_name = /((^|[\r\n{,;])[ \t]*["']?((full[_ \t-]*name|name))["']?[ \t]*[:=][ \t]*["']?([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])(([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])|['-]){0,39}[ \t]+([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])(([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])|['-]){0,39}([ \t]+([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])(([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])|['-]){0,39}){0,2}(["']|[ \t,;}\r\n]|$))/ nocase
        $first_name = /((^|[\r\n{,;])[ \t]*["']?(first[_ \t-]*name)["']?[ \t]*[:=][ \t]*["']?([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])(([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])|['-]){0,39}([ \t]+([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])(([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])|['-]){0,39}){0,2}(["']|[ \t,;}\r\n]|$)|(^|[\r\n{,;])[ \t]*["']?(given[_ \t-]*name)["']?[ \t]*[:=][ \t]*["']?([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])(([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])|['-]){0,39}([ \t]+([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])(([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])|['-]){0,39}){0,2}(["']|[ \t,;}\r\n]|$))/ nocase
        $last_name = /((^|[\r\n{,;])[ \t]*["']?(last[_ \t-]*name)["']?[ \t]*[:=][ \t]*["']?([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])(([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])|['-]){0,39}([ \t]+([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])(([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])|['-]){0,39}){0,2}(["']|[ \t,;}\r\n]|$)|(^|[\r\n{,;])[ \t]*["']?(family[_ \t-]*name)["']?[ \t]*[:=][ \t]*["']?([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])(([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])|['-]){0,39}([ \t]+([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])(([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])|['-]){0,39}){0,2}(["']|[ \t,;}\r\n]|$)|(^|[\r\n{,;])[ \t]*["']?(surname)["']?[ \t]*[:=][ \t]*["']?([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])(([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])|['-]){0,39}([ \t]+([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])(([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])|['-]){0,39}){0,2}(["']|[ \t,;}\r\n]|$))/ nocase
    condition:
        (helper_pri_en or helper_pri_long_en) and ((helper_full_en) or ((helper_first_en or helper_given_en) and (helper_last_en or helper_family_en or helper_surname_en)))
        and $identifier and ($full_name or ($first_name and $last_name))
}

rule personal_pri_fr : personal_information classification
{
    meta:
        title = "Personnel identifier with a name (FR)"
        severity = "MEDIUM"
        suggested_classification = "Protected A"
        assessment = "review_required"
        evidence_model = "identifier_and_name"
        match_scope = "file"
    strings:
        $identifier = /((^|[\r\n{,;])[ \t]*["']?(CIDP)["']?[ \t]*([:=][ \t]*|[ \t]+)["']?([0-9]{8,9}|[0-9]{2,3}[-. ][0-9]{3}[-. ][0-9]{3})\b|(^|[\r\n{,;])[ \t]*["']?(code[_ \t-]*d('|\xE2\x80\x99)identification[_ \t-]*de[_ \t-]*dossier[_ \t-]*personnel)["']?[ \t]*([:=][ \t]*|[ \t]+)["']?([0-9]{8,9}|[0-9]{2,3}[-. ][0-9]{3}[-. ][0-9]{3})\b)/ nocase
        $full_name = /((^|[\r\n{,;])[ \t]*["']?(nom)["']?[ \t]*[:=][ \t]*["']?([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])(([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])|['-]){0,39}[ \t]+([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])(([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])|['-]){0,39}([ \t]+([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])(([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])|['-]){0,39}){0,2}(["']|[ \t,;}\r\n]|$))/ nocase
        $first_name = /((^|[\r\n{,;])[ \t]*["']?(pr(e|\xC3\xA9|\xC3\x89)nom)["']?[ \t]*[:=][ \t]*["']?([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])(([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])|['-]){0,39}([ \t]+([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])(([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])|['-]){0,39}){0,2}(["']|[ \t,;}\r\n]|$))/ nocase
        $last_name = /((^|[\r\n{,;])[ \t]*["']?(nom[_ \t-]*de[_ \t-]*famille)["']?[ \t]*[:=][ \t]*["']?([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])(([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])|['-]){0,39}([ \t]+([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])(([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])|['-]){0,39}){0,2}(["']|[ \t,;}\r\n]|$))/ nocase
    condition:
        (helper_cidp_fr or helper_cidp_long_fr) and ((helper_full_fr) or ((helper_first_fr) and (helper_last_fr)))
        and $identifier and ($full_name or ($first_name and $last_name))
}
