"""Generate modular YARA from one pattern catalogue. Run after editing patterns."""
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[1]
# Bound labels to a line or a record/property separator. Avoid finding Name inside First Name.
PREFIX = r'''(^|[\r\n{,;])[ \t]*["']?'''
SEP = r'''["']?[ \t]*([:=][ \t]*|[ \t]+)["']?'''
LETTER = r'([A-Za-z]|\xC3[\x80-\x96\x98-\xB6\xB8-\xBF])'
WORD = LETTER + r"(" + LETTER + r"|['-]){0,39}"
END = r'''(["']|[ \t,;}\r\n]|$)'''
PART = WORD + r'([ \t]+' + WORD + r'){0,2}' + END
FULL = WORD + r'[ \t]+' + WORD + r'([ \t]+' + WORD + r'){0,2}' + END
PRI = r'([0-9]{8,9}|[0-9]{2,3}[-. ][0-9]{3}[-. ][0-9]{3})\b'
SIN = r'([0-9]{9}|[0-9]{3}[-. ][0-9]{3}[-. ][0-9]{3})\b'
DOB = r'(18|19|20)[0-9]{2}[-.\/](0?[1-9]|1[0-2])[-.\/](0?[1-9]|[12][0-9]|3[01])\b'
GAP = r'[_ \t-]*'
LABELS = {
 'pri_en': ('identifiers', 'PRI', PRI),
 'pri_long_en': ('identifiers', 'personal'+GAP+'record'+GAP+'identifier', PRI),
 'cidp_fr': ('identifiers', 'CIDP', PRI),
 'cidp_long_fr': ('identifiers', r"code"+GAP+r"d('|\xE2\x80\x99)identification"+GAP+'de'+GAP+'dossier'+GAP+'personnel', PRI),
 'sin_en': ('identifiers', 'SIN', SIN),
 'sin_long_en': ('identifiers', 'social'+GAP+'insurance'+GAP+'number', SIN),
 'nas_fr': ('identifiers', 'NAS', SIN),
 'nas_long_fr': ('identifiers', r'num(e|\xC3\xA9|\xC3\x89)ro'+GAP+r"d('|\xE2\x80\x99)assurance"+GAP+'sociale', SIN),
 'first_en': ('names', 'first'+GAP+'name', PART),
 'given_en': ('names', 'given'+GAP+'name', PART),
 'last_en': ('names', 'last'+GAP+'name', PART),
 'family_en': ('names', 'family'+GAP+'name', PART),
 'surname_en': ('names', 'surname', PART),
 'full_en': ('names', '(full'+GAP+'name|name)', FULL),
 'first_fr': ('names', r'pr(e|\xC3\xA9|\xC3\x89)nom', PART),
 'last_fr': ('names', 'nom'+GAP+'de'+GAP+'famille', PART),
 'full_fr': ('names', 'nom', FULL),
 'dob_en': ('dates', 'DOB', DOB),
 'dob_long_en': ('dates', 'date'+GAP+'of'+GAP+'birth', DOB),
 'dob_fr': ('dates', 'DDN', DOB),
 'dob_long_fr': ('dates', 'date'+GAP+'de'+GAP+'naissance', DOB),
}

def q(value): return json.dumps(value, ensure_ascii=False)
def expr(key):
 group,label,value=LABELS[key]
 separator = r'''["']?[ \t]*[:=][ \t]*["']?''' if group == 'names' else SEP
 return PREFIX+'('+label+')'+separator+value

def generate():
 files={group:[] for group in ('identifiers','names','dates')}
 for key,(group,_,_) in LABELS.items():
  files[group].append(f'private rule helper_{key} : helper\n{{\n    strings:\n        $value = /{expr(key)}/ nocase\n    condition:\n        $value\n}}\n')
 for group,blocks in files.items():
  (ROOT/'rules/indicators'/f'{group}.yar').write_text('// Generated by tools/build_rules.py\n\n'+'\n'.join(blocks))
 for kind,labels in {'pri':{'en':['pri_en','pri_long_en'],'fr':['cidp_fr','cidp_long_fr']},'dob':{'en':['dob_en','dob_long_en'],'fr':['dob_fr','dob_long_fr']},'sin':{'en':['sin_en','sin_long_en'],'fr':['nas_fr','nas_long_fr']}}.items():
  blocks=[]
  for lang,ids in labels.items():
   first=['first_en','given_en'] if lang=='en' else ['first_fr']
   last=['last_en','family_en','surname_en'] if lang=='en' else ['last_fr']
   full=['full_'+lang]
   roles={'identifier':ids,'full_name':full,'first_name':first,'last_name':last}
   def refs(keys):return '('+' or '.join('helper_'+k for k in keys)+')'
   condition=refs(ids)+' and ('+refs(full)+' or ('+refs(first)+' and '+refs(last)+'))'
   title={'pri':'Personnel identifier','dob':'Date of birth','sin':'Social Insurance Number'}[kind]+' with a name ('+lang.upper()+')'
   cls='Protected B' if kind=='sin' else 'Protected A'
   lines=[f'rule personal_{kind}_{lang} : personal_information classification', '{', '    meta:',f'        title = {q(title)}',f'        severity = {q("HIGH" if kind=="sin" else "MEDIUM")}',f'        suggested_classification = {q(cls)}','        assessment = "review_required"','        evidence_model = "identifier_and_name"','        match_scope = "file"','    strings:']
   for role,keys in roles.items():lines.append('        $'+role+' = /('+'|'.join(expr(k) for k in keys)+')/ nocase')
   # Referenced helper strings are not returned with composite matches. These
   # mirrored, generated strings expose their locations for SARIF and PR comparison.
   lines+=['    condition:','        '+condition,'        and $identifier and ($full_name or ($first_name and $last_name))','}','']
   blocks.append('\n'.join(lines))
  (ROOT/'rules/logic'/f'{kind}-with-name.yar').write_text('// Generated by tools/build_rules.py; shared helpers plus reportable evidence.\n\n'+'\n'.join(blocks))
 marks=[('nato_restricted_en','NATO Restricted',r'\bNATO[ _\t-]+RESTRICTED\b','MEDIUM'),
        ('nato_restricted_fr','OTAN Diffusion restreinte',r'\bOTAN[ _\t-]+DIFFUSION[ _\t-]+RESTREINTE\b','MEDIUM'),
        ('nato_unclassified_en','NATO Unclassified',r'\bNATO[ _\t-]+UNCLASSIFIED\b','LOW'),
        ('nato_unclassified_fr','OTAN Non-classifié',r'\bOTAN[ _\t-]+NON[ _-]+CLASSIFI(\xC3\x89|\xC3\xA9)','LOW'),
        ('uk_official_en','UK Official',r'\bUK[ _\t:-]+OFFICIAL\b','MEDIUM'),
        ('uk_official_fr','RU Officiel',r'\bRU[ _\t:-]+OFFICIEL\b','MEDIUM')]
 blocks=[]
 for ident,title,pattern,severity in marks:
  blocks.append(f'rule marking_{ident} : security_marking\n{{\n    meta:\n        title = {q(title+" marking")}\n        severity = {q(severity)}\n        evidence_model = "marking"\n        assessment = "review_required"\n    strings:\n        $marking = /{pattern}/ nocase\n    condition:\n        $marking\n}}\n')
 (ROOT/'rules/logic/security-markings.yar').write_text('// Optional text indicators, including two Unclassified labels.\n\n'+'\n'.join(blocks))
 # Explicit true flags for every term in the GC sensitivity grid. These are
 # assertions to review; a flag does not prove that the contents merit its label.
 flags=[('protected','Protected','Protégé','LOW'),
        ('protected_a','Protected A','Protégé A','MEDIUM'),
        ('protected_b','Protected B','Protégé B','HIGH'),
        ('protected_c','Protected C','Protégé C','CRITICAL'),
        ('classified','Classified','Classifié','LOW'),
        ('confidential','Confidential','Confidentiel','MEDIUM'),
        ('secret','Secret','Secret','HIGH'),
        ('top_secret','Top Secret','Très secret','CRITICAL'),
        ('unclassified','Unclassified','Non classifié','LOW'),
        ('protected_when_completed','Protected when Completed','Protégé lorsque rempli','LOW')]
 blocks=[]
 for ident,english,french,severity in flags:
  # Secret has the same spelling in both languages; report it only once.
  variants=[('',english)] if english==french else [('_en',english),('_fr',french)]
  for suffix,label in variants:
   label_pattern=label.replace(' ',r'[ _-]+').replace('é',r'(e|\xC3\xA9|\xC3\x89)').replace('è',r'(e|\xC3\xA8|\xC3\x88)')
   pattern=r'(^|[\r\n])[ \t]*"'+label_pattern+r'"[ \t]*:[ \t]*"true"[ \t]*(\r?\n|$)'
   blocks.append(f'rule flag_{ident}{suffix} : security_marking classification\n{{\n    meta:\n        title = {q(label+" flag is enabled")}\n        severity = {q(severity)}\n        suggested_classification = {q(english)}\n        evidence_model = "marking"\n        assessment = "review_required"\n    strings:\n        $marking = /{pattern}/ nocase\n    condition:\n        $marking\n}}\n')
 (ROOT/'rules/logic/classification-flags.yar').write_text('// Generated by tools/build_rules.py; requires structured field normalization.\n\n'+'\n'.join(blocks))
 (ROOT/'rules/profiles/code.yar').write_text('\n'.join('include "../'+p+'.yar"' for p in ('indicators/identifiers','indicators/names','indicators/dates','logic/pri-with-name','logic/dob-with-name','logic/sin-with-name'))+'\n')
 (ROOT/'rules/profiles/code-with-markings.yar').write_text('include "code.yar"\ninclude "../logic/security-markings.yar"\ninclude "../logic/classification-flags.yar"\n')

if __name__=='__main__':generate()
